application: dabblinginanalytics
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico
- url: /*.otf
  static_dir: fonts
- url: /*.ttf
  static_dir: fonts
- url: /*.css
  static_dir: css
- url: /*.js
  static_dir: js
- url: /.*
  script: dabblinginanalytics.application

libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest